/**
 * Build a STATIC snapshot of the current scanner.db for Vercel (or any static
 * host). Exports shops/products/config to JSON and writes self-contained HTML
 * pages that read those files client-side. Output → ./web-static/
 *
 *   node build-static.js   (or: npm run build:static)
 *
 * No server, no browser. To refresh: re-run scan/products locally, rebuild,
 * redeploy. Live "Analyze" and scanning are NOT part of the static snapshot.
 */
'use strict';

const fs = require('fs');
const path = require('path');
const store = require('./db');
const { CONFIG } = require('./uzum-scanner');

const OUT = path.join(__dirname, 'web-static');
const DATA = path.join(OUT, 'data');
const API = path.join(OUT, 'api');
fs.mkdirSync(DATA, { recursive: true });
fs.mkdirSync(API, { recursive: true });

// --- data ---
const shops = store.listShops();
const { rows: products } = store.listProducts({ limit: 1e9, offset: 0 });
const config = {
  pricePerImage: CONFIG.PRICE_PER_IMAGE,
  imagesPerProduct: CONFIG.IMAGES_PER_PRODUCT,
  productsPerPage: CONFIG.PRODUCTS_PER_PAGE,
  generatedAt: new Date().toISOString(),
};

fs.writeFileSync(path.join(DATA, 'shops.json'), JSON.stringify(shops));
fs.writeFileSync(path.join(DATA, 'products.json'), JSON.stringify(products));
fs.writeFileSync(path.join(DATA, 'config.json'), JSON.stringify(config));

const totalProducts = shops.reduce((a, s) => a + (s.last_count || 0), 0);

// --- api/analyze.js — Vercel serverless function (pure HTTP, no browser) ---
// Mints an anonymous Uzum token, resolves the shop, reads exact product total.
fs.writeFileSync(path.join(API, 'analyze.js'), `'use strict';
// Auto-generated by build-static.js. Native Vercel analyze — no browser needed:
// uzum mints an anonymous Bearer via POST id.uzum.uz/api/auth/token (no captcha).
const crypto = require('crypto');
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';
const PRICE_PER_IMAGE = ${CONFIG.PRICE_PER_IMAGE};
const IMAGES_PER_PRODUCT = ${CONFIG.IMAGES_PER_PRODUCT};
const PRODUCTS_PER_PAGE = ${CONFIG.PRODUCTS_PER_PAGE};
const Q = \`query MakeSearch_ItemsAndFilters($queryInput: MakeSearchQueryInput!) { makeSearch(query: $queryInput) { total __typename } }\`;

let cached = null; // { token, iid, exp }

async function mintToken() {
  const r = await fetch('https://id.uzum.uz/api/auth/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: 'Bearer', 'User-Agent': UA, Referer: 'https://uzum.uz/', Origin: 'https://uzum.uz', 'Accept-Language': 'uz' },
  });
  const sc = r.headers.getSetCookie ? r.headers.getSetCookie() : [r.headers.get('set-cookie')];
  const line = (sc || []).find((c) => c && c.startsWith('access_token='));
  const token = line ? line.split('access_token=')[1].split(';')[0] : null;
  if (!token) throw new Error('token mint failed (HTTP ' + r.status + ')');
  cached = { token, iid: crypto.randomUUID(), exp: Date.now() + 5 * 3600 * 1000 };
  return cached;
}
async function session() {
  if (cached && Date.now() < cached.exp) return cached;
  return mintToken();
}
function parseSlug(input) {
  if (!input) return null;
  const s = String(input).trim();
  if (!s.includes('/')) return s || null;
  const m = s.match(/\\/(?:seller|shop)\\/([^/?#]+)/i);
  return m ? m[1] : null;
}

module.exports = async (req, res) => {
  const input = (req.query.input || '').toString().trim();
  if (!input) return res.status(400).json({ ok: false, error: 'Provide ?input=<shop URL or slug>' });
  const slug = parseSlug(input);
  if (!slug) return res.status(400).json({ ok: false, error: 'Could not parse a shop URL or slug.' });

  try {
    let s = await session();
    const auth = () => ({ Authorization: 'Bearer ' + s.token, 'x-iid': s.iid, 'User-Agent': UA, Referer: 'https://uzum.uz/', Origin: 'https://uzum.uz', 'Accept-Language': 'uz-UZ', Accept: 'application/json' });

    let shopRes = await fetch('https://api.uzum.uz/api/shop/' + encodeURIComponent(slug), { headers: auth() });
    if (shopRes.status === 401) { s = await mintToken(); shopRes = await fetch('https://api.uzum.uz/api/shop/' + encodeURIComponent(slug), { headers: auth() }); }
    if (shopRes.status === 404) return res.status(404).json({ ok: false, error: 'Shop not found for "' + slug + '".' });
    const shopJson = await shopRes.json().catch(() => null);
    const shop = shopJson && shopJson.payload;
    if (!shop || !shop.id) return res.status(404).json({ ok: false, error: 'Shop not found for "' + slug + '".' });

    const gqlRes = await fetch('https://graphql.uzum.uz/', {
      method: 'POST',
      headers: { ...auth(), 'Content-Type': 'application/json', 'apollographql-client-name': 'web-customers', 'apollographql-client-version': '1.63.2', 'city-id': '1' },
      body: JSON.stringify({ operationName: 'MakeSearch_ItemsAndFilters', query: Q, variables: { queryInput: { showAdultContent: 'NONE', filters: [], sort: 'BY_ORDERS_NUMBER_DESC', pagination: { offset: 0, limit: 1 }, correctQuery: false, getFastCategories: false, getPromotionItems: false, getFastFacets: false, shopId: String(shop.id), categoryId: null } } }),
    });
    const gqlJson = await gqlRes.json().catch(() => null);
    const total = gqlJson && gqlJson.data && gqlJson.data.makeSearch && gqlJson.data.makeSearch.total;
    if (total == null) return res.status(502).json({ ok: false, error: 'Product count failed (upstream).' });

    const images = total * IMAGES_PER_PRODUCT;
    res.json({ ok: true, id: shop.id, title: shop.title, slug: shop.link, url: 'https://uzum.uz/uz/seller/' + shop.link,
      rating: shop.rating ?? null, orders: shop.orders ?? null,
      productCount: total, approxPages: Math.ceil(total / PRODUCTS_PER_PAGE), imagesYouCanCreate: images, quote: images * PRICE_PER_IMAGE });
  } catch (err) {
    res.status(502).json({ ok: false, error: String(err.message || err) });
  }
};
`);

// --- shared head/style ---
const STYLE = `
  :root { --uzum: #7000ff; --bg: #f4f4f8; }
  * { box-sizing: border-box; }
  body { margin:0; font-family:-apple-system,Segoe UI,Roboto,sans-serif; background:var(--bg); color:#1f2026; padding:32px; }
  .head { display:flex; align-items:center; justify-content:space-between; margin-bottom:16px; flex-wrap:wrap; gap:8px; }
  h1 { margin:0; font-size:22px; }
  .links a { text-decoration:none; color:var(--uzum); font-weight:600; font-size:14px; margin-left:16px; }
  .totals { display:flex; gap:14px; margin-bottom:20px; flex-wrap:wrap; }
  .tcard { background:#fff; border-radius:12px; padding:16px 20px; box-shadow:0 4px 18px rgba(0,0,0,.06); }
  .tcard .label { font-size:12px; color:#6b6b76; } .tcard .value { font-size:26px; font-weight:700; margin-top:2px; }
  .tcard.hl .value { color:var(--uzum); }
  table { width:100%; border-collapse:collapse; background:#fff; border-radius:12px; overflow:hidden; box-shadow:0 4px 18px rgba(0,0,0,.06); }
  th,td { text-align:left; padding:12px 14px; font-size:14px; border-bottom:1px solid #eee; }
  th { background:#faf8ff; color:#555; font-size:12px; text-transform:uppercase; letter-spacing:.3px; }
  tr:last-child td { border-bottom:0; } td.num,th.num { text-align:right; font-variant-numeric:tabular-nums; }
  .rank { color:#999; width:36px; } .pill { font-size:11px; padding:2px 8px; border-radius:99px; background:#eee; color:#666; margin-left:6px; }
  a.cell { color:var(--uzum); text-decoration:none; font-weight:600; }
  .controls { display:flex; gap:10px; margin-bottom:16px; flex-wrap:wrap; }
  input,select { padding:10px 12px; font-size:14px; border:1px solid #d8d8e0; border-radius:10px; outline:none; }
  input:focus,select:focus { border-color:var(--uzum); } input#q { flex:1; min-width:220px; }
  .pager { display:flex; align-items:center; gap:12px; margin-top:16px; justify-content:center; }
  .pager button { padding:8px 16px; border:1px solid #d8d8e0; background:#fff; border-radius:8px; cursor:pointer; }
  .pager button:disabled { opacity:.4; cursor:default; } .count { color:#6b6b76; font-size:13px; }
  .note { color:#6b6b76; font-size:13px; margin-top:8px; }
  .tablewrap { overflow-x:auto; -webkit-overflow-scrolling:touch; border-radius:12px; }
  .tablewrap table { min-width:640px; }
  select { max-width:100%; }
  @media (max-width:600px) {
    body { padding:16px; }
    h1 { font-size:19px; }
    th,td { padding:10px 10px; font-size:13px; }
    .tcard { padding:12px 16px; } .tcard .value { font-size:22px; }
    .links a { margin-left:10px; font-size:13px; }
    .controls { flex-direction:column; } input#q, select { width:100%; }
  }
`;
const ESC = `const esc=(s)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n)=>n==null?'—':Number(n).toLocaleString('en-US');`;
const NAV = (active) => `<div class="links">
  ${active !== 'home' ? '<a href="./index.html">Top shops</a>' : ''}
  ${active !== 'products' ? '<a href="./products.html">All products</a>' : ''}
  <a href="https://github.com/azimrkhmv/uzumscanner" target="_blank" rel="noopener">GitHub</a>
</div>`;

// --- index.html (top shops + totals) ---
fs.writeFileSync(path.join(OUT, 'index.html'), `<!DOCTYPE html><html lang="en"><head>
<meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Uzum — Top Shops</title><style>${STYLE}</style></head><body>
<div class="head"><h1>Uzum Top Shops</h1>${NAV('home')}</div>
<div style="background:#fff;border-radius:12px;padding:18px 20px;box-shadow:0 4px 18px rgba(0,0,0,.06);margin-bottom:20px">
  <div style="font-weight:700;margin-bottom:8px">Analyze any shop — instant quote</div>
  <div class="controls" style="margin-bottom:0">
    <input id="ainput" placeholder="https://uzum.uz/uz/seller/…  or  dafna" autocomplete="off"/>
    <button id="abtn" style="padding:10px 20px;font-weight:600;color:#fff;background:var(--uzum);border:0;border-radius:10px;cursor:pointer">Analyze</button>
  </div>
  <div id="aerr" style="color:#c0392b;font-size:13px;margin-top:8px;display:none"></div>
  <div id="ares" style="display:none;margin-top:14px">
    <div style="font-weight:700;font-size:16px" id="aname"></div>
    <div class="totals" style="margin-top:10px;margin-bottom:0">
      <div class="tcard"><div class="label">Products</div><div class="value" id="acount"></div></div>
      <div class="tcard"><div class="label">Pages</div><div class="value" id="apages"></div></div>
      <div class="tcard"><div class="label">Images</div><div class="value" id="aimg"></div></div>
      <div class="tcard hl"><div class="label">Quote (so'm)</div><div class="value" id="aquote"></div></div>
    </div>
  </div>
</div>
<div class="totals">
  <div class="tcard"><div class="label">Shops</div><div class="value">${shops.length}</div></div>
  <div class="tcard hl"><div class="label">Total products (all shops)</div><div class="value">${totalProducts.toLocaleString('en-US')}</div></div>
</div>
<div class="tablewrap"><table><thead><tr><th class="rank">#</th><th>Shop</th><th class="num">Products</th><th class="num">Rating</th><th class="num">Orders</th><th class="num">Quote (so'm)</th><th>Catalog</th></tr></thead>
<tbody id="rows"><tr><td colspan="7">Loading…</td></tr></tbody></table></div>
<p class="note">Static snapshot · generated ${config.generatedAt}. Live analyze & scanning run from the local app.</p>
<script>${ESC}
const A=(id)=>document.getElementById(id);
async function analyze(){const v=A('ainput').value.trim();if(!v)return;
 A('abtn').disabled=true;A('abtn').textContent='…';A('aerr').style.display='none';A('ares').style.display='none';
 try{const d=await (await fetch('/api/analyze?input='+encodeURIComponent(v))).json();
  if(!d.ok)throw new Error(d.error||'failed');
  A('aname').textContent=d.title+' · '+(d.rating!=null?d.rating+'★ · ':'')+fmt(d.orders)+' orders';
  A('acount').textContent=fmt(d.productCount);A('apages').textContent=fmt(d.approxPages);
  A('aimg').textContent=fmt(d.imagesYouCanCreate);A('aquote').textContent=fmt(d.quote);
  A('ares').style.display='block';
 }catch(e){A('aerr').textContent=e.message;A('aerr').style.display='block';}
 finally{A('abtn').disabled=false;A('abtn').textContent='Analyze';}}
A('abtn').onclick=analyze;A('ainput').addEventListener('keydown',e=>{if(e.key==='Enter')analyze();});
fetch('./data/config.json').then(r=>r.json()).then(cfg=>{
 fetch('./data/shops.json').then(r=>r.json()).then(shops=>{
  const tb=document.getElementById('rows'); tb.innerHTML='';
  shops.forEach((s,i)=>{const url='https://uzum.uz/uz/seller/'+encodeURIComponent(s.slug||'');
   const quote=(s.last_count||0)*cfg.pricePerImage; const tr=document.createElement('tr');
   tr.innerHTML='<td class="rank">'+(i+1)+'</td>'+
    '<td><a class="cell" href="'+esc(url)+'" target="_blank" rel="noopener">'+esc(s.title)+'</a><span class="pill">#'+s.shop_id+'</span></td>'+
    '<td class="num">'+fmt(s.last_count)+'</td><td class="num">'+(s.rating!=null?s.rating+' ★':'—')+'</td>'+
    '<td class="num">'+fmt(s.orders)+'</td><td class="num">'+fmt(quote)+'</td>'+
    '<td><a class="cell" href="./products.html?shop='+s.shop_id+'">View →</a></td>';
   tb.appendChild(tr);});
 });});
</script></body></html>`);

// --- products.html (client-side search + filter + paginate) ---
fs.writeFileSync(path.join(OUT, 'products.html'), `<!DOCTYPE html><html lang="en"><head>
<meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Uzum — All Products</title><style>${STYLE}</style></head><body>
<div class="head"><h1>All Products</h1>${NAV('products')}</div>
<div class="controls"><input id="q" placeholder="Search product title…" autocomplete="off"/>
<select id="shop"><option value="">All shops</option></select></div>
<div class="count" id="count"></div>
<div class="tablewrap"><table><thead><tr><th>Product</th><th>Shop</th><th class="num">Price (so'm)</th></tr></thead>
<tbody id="rows"><tr><td colspan="3">Loading…</td></tr></tbody></table></div>
<div class="pager"><button id="prev">← Prev</button><span class="count" id="pageinfo"></span><button id="next">Next →</button></div>
<script>${ESC}
const LIMIT=50; let ALL=[],view=[],offset=0,q='',shop=new URLSearchParams(location.search).get('shop')||'';
const $=(id)=>document.getElementById(id);
Promise.all([fetch('./data/products.json').then(r=>r.json()),fetch('./data/shops.json').then(r=>r.json())]).then(([prods,shops])=>{
 ALL=prods;
 for(const s of shops){const o=document.createElement('option');o.value=s.shop_id;o.textContent=s.title+' ('+fmt(s.last_count)+')';if(String(s.shop_id)===String(shop))o.selected=true;$('shop').appendChild(o);}
 apply();
});
function apply(){const ql=q.toLowerCase();
 view=ALL.filter(p=>(!shop||String(p.shop_id)===String(shop))&&(!ql||(p.title||'').toLowerCase().includes(ql)));
 view.sort((a,b)=>(b.price||0)-(a.price||0)); offset=0; render();}
function render(){const tb=$('rows'); const page=view.slice(offset,offset+LIMIT);
 if(!page.length){tb.innerHTML='<tr><td colspan="3">No matches.</td></tr>';}
 else{tb.innerHTML='';for(const p of page){const purl='https://uzum.uz/uz/product/'+encodeURIComponent(p.product_id);
  const surl='https://uzum.uz/uz/seller/'+encodeURIComponent(p.shop_slug||'');const tr=document.createElement('tr');
  tr.innerHTML='<td><a class="cell" style="color:#1f2026" href="'+esc(purl)+'" target="_blank" rel="noopener">'+esc(p.title||'(untitled)')+'</a></td>'+
   '<td><a class="cell" href="'+esc(surl)+'" target="_blank" rel="noopener">'+esc(p.shop_title)+'</a></td>'+
   '<td class="num">'+fmt(p.price)+'</td>'; tb.appendChild(tr);} }
 $('count').textContent=fmt(view.length)+' products'+(shop?' in this shop':' across all shops');
 const from=view.length?offset+1:0,to=Math.min(offset+LIMIT,view.length);
 $('pageinfo').textContent=from+'–'+to+' of '+fmt(view.length);
 $('prev').disabled=offset===0; $('next').disabled=offset+LIMIT>=view.length;}
let t;$('q').oninput=()=>{clearTimeout(t);t=setTimeout(()=>{q=$('q').value.trim();apply();},250);};
$('shop').onchange=()=>{shop=$('shop').value;apply();};
$('prev').onclick=()=>{offset=Math.max(0,offset-LIMIT);render();};
$('next').onclick=()=>{offset+=LIMIT;render();};
</script></body></html>`);

console.log(`Static snapshot → ${OUT}`);
console.log(`  ${shops.length} shops, ${products.length} products, total ${totalProducts.toLocaleString('en-US')}`);
console.log('Deploy: cd web-static && vercel');
